### ISSUE TITLE
Failed in hiding strings

### ISSUE THREAD

**Issue by rynnwang** [lextm/obfuscar#116]
Obfuscar.2.2.6

Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at Mono.Cecil.Rocks.MethodBodyRocks.OptimizeMacros(MethodBody self)
   at Obfuscar.Obfuscator.StringSqueeze.ProcessStrings(MethodDefinition method, AssemblyInfo info, Project project)
   at Obfuscar.Obfuscator.HideStrings()
   at Obfuscar.Obfuscator.RunRules()
   at Obfuscar.Program.Main(String[] args)

**Comment by lextm** [comment]
You can set `OptimizeMethods` to `false` so as to avoid this exception.

The exception comes from Mono Cecil, so no way to fix it in Obfuscar.

**Comment by mailbee** [comment]
I'm getting the same exception (Obfuscar 2.2.8) when processing .netstandard2.0 dll. My xml config is like this:

	<?xml version='1.0'?>
	<Obfuscator>
	  <Var name="InPath" value="." />
	  <Var name="OutPath" value=".\Obfuscated" />
	  <Var name="HidePrivateApi" value="true" />
	  <Var name="OptimizeMethods" value="false" />
	  <Var name="KeyFile" value="$(InPath)\private.snk" />
	  <Module file="$(InPath)\Foo.NET.dll" />
	</Obfuscator>

"OptimizeMethods" does not seem to have any effect.

**Comment by lextm** [comment]
Can you provide a sample to reproduce the error? 

If confidential, you can send it to support@lextm.com. If not confidential, you might upload to this issue at GitHub directly.

**Comment by mailbee** [comment]
I sent a test project to support@lextm.com email (as it's pretty big).

**Comment by lextm** [comment]
Received. I will do some digging.

**Comment by mailbee** [comment]
OK, I did some more testing trying to narrow down the issue and throwing away more and more code. Finally, I found the problematic place. This is the shortest code which reproduces "Specified cast is not valid" problem:

	class MyClass
	{
		long someValue = -276939487313920L;
	}

**Comment by lextm** [comment]
Please upgrade to 2.2.9 release which fixed the OptimizeMethods issue. Now by setting this variable to `false`, there should be no exception.
