### ISSUE TITLE
"Saving assemblies..." - IOException

### ISSUE THREAD

**Issue by aaad** [lextm/obfuscar#117]
I just upgraded from 2.2.2 to 2.2.6 and now I am getting IOExceptions.

I do the following: 

1) I copy \tfs\foobar\bin\Debug to \tfs\foobar\bin\Debug2 (to ensure that there is no write access to Debug2)
2) I call ..\..\..\packages\Obfuscar.2.2.6\tools\Obfuscar.Console.exe obfuscar.xml in Debug2\
3) Message:

> Loading project obfuscar.xml...Processing assembly: foobar.foobarName, Version=105.1.0.56, Culture=neutral, PublicKeyToken=212da3724f4b6cdf
> [...] Some more assemblies
> Loading assemblies...Extra framework folders: Done.
> hiding strings...
> Renaming:  fields...parameters...properties...events...methods...types...Done.
> Saving assemblies...
> Failed to save foobar.foobarName.dll
> IOException: Der Prozess kann nicht auf die Datei "D:\Workspaces\tfs\foobar\bin\Debug2\foobar.foobarName.dll" zugreifen, da sie von einem anderen Prozess verwendet wird.
> Failed to save foobar.foobarName.dll
> [...] <- same for all other assemblies
> Writing log file...Done.
> Completed, 2,50 secs.

My obfuscar.xml looks like this:

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\" />
  <Var name="OutPath" value=".\" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="KeyFile" value=".\foobar.snk" />

  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="HideStrings" value="true" />


  <Module file="$(InPath)\foobar.foobarName.dll"/>
[...] <- more modules

</Obfuscator>

```

Isn't it possible anymore to keep the files in the same directory?

**Comment by lextm** [comment]
It seems to be a Mono.Cecil issue. More investigation is required.

**Comment by brinkdinges** [comment]
Has anyone looked in to this? I'm having the same issue. 

I doubt I can be of service, but I'm willing to try if someone can point me in the right direction.

**Comment by lextm** [comment]
`<Var name="OutPath" value=".\" />` is the cause. You need to set it to another location, and don't overwrite the original assembly.

As it is a limitation of Mono Cecil, this project won't attempt to fix it.
