### ISSUE TITLE
The solution contained in released zip won't compile.

### ISSUE THREAD

**Issue by zwcloud** [lextm/obfuscar#118]
For example,

https://github.com/lextm/obfuscar/releases/tag/2.2.6

Because the source files in submodule _ilspy@6a58560_ wasn't included.

**Comment by lextm** [comment]
Dup #69

**Comment by zwcloud** [comment]
Cloned via git, but still get errors:

>\obfuscar\Console\Program.cs(33,7,33,11): error CS0246: The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)
> \obfuscar\Console\Program.cs(34,7,34,20): error CS0246: The type or namespace name 'RollbarDotNet' could not be found (are you missing a using directive or an assembly referenc
> \obfuscar\Console\Program.cs(42,38,42,47): error CS0246: The type or namespace name 'OptionSet' could not be found (are you missing a using directive or an assembly reference?)

**Comment by zwcloud** [comment]
Finally it compiles successfully. Thanks~

**Comment by lextm** [comment]
You have to check out the code of this repo via Git, and also check out all the submodules.

**Comment by lextm** [comment]
Duplicate to #96
