### ISSUE TITLE
Don't support .NET Core 2.0.

### ISSUE THREAD

**Issue by zwcloud** [lextm/obfuscar#119]
> Failed to resolve assembly: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

possibly related:
https://stackoverflow.com/q/45021965/3427520

**Comment by lextm** [comment]
.NET Standard 2.0 support would require quite some efforts.

Current you might try the following,

1. Check out master.
2. Run with the following configuration, to disable string hiding and SuppressIldasm attribute insertion.
```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\Obfuscator_Output" />
  <Var name="HideStrings" value="false" />
  <Var name="SuppressIldasm" value="false" />
  
  <Module file="$(InPath)\ClassLibrary1.dll" />
  <AssemblySearchPath path="c:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\" />
</Obfuscator>
```
More investigation would be required before an official announcement on full support.

**Comment by lextm** [comment]
Shipped 2.2.7 release, which is tested against a few .NET Standard 2.0 assemblies.

Close this item temporarily, and will revisit if issues observed in the future.

**Comment by breyed** [comment]
For reference purposes, the related .NET Standard issue is dotnet/runtime#8800.

**Comment by breyed** [comment]
Is there a workaround for building on a Mac? When I use Obfuscar 2.2.25 on Windows when building a Xamarin.Android project, the app works fine, even without an AssemblySearchPath. If I build the same project on a Mac, the app crashes with "Could not load file or assembly 'netstandard...", even if I include this in obfuscar.xml:

```
<AssemblySearchPath path="/usr/local/share/dotnet/sdk/NuGetFallbackFolder/microsoft.netcore.app/2.1.0/ref/netcoreapp2.1/" />
```
