### ISSUE TITLE
I don't understand HideStrings setting

### ISSUE THREAD

**Issue by wolfgangschneider** [lextm/obfuscar#122]
Hi

Can someone advice me how to hide strings ?

private const string MyString = "Hallo World"; will only translated to  
private const string A = "Hallo World";

I guess I understood something wrong. Anyhow , is it possible to obfuscate strings  ?

Wolfgang

**Comment by ZimM-LostPolygon** [comment]
You are not doing anything wrong. Strings are obfuscated at the call site by replacing the `ldstr` instruction with some code that returns the real string. Class-level constants, however, can't be obfuscated, since they are basically a blob of data, and not code. 

However, I think it would make sense to remove class-level private constants from the assembly entirely...

**Comment by XenocodeRCE** [comment]
```csharp
public class MyClass
{
	public const string MyString = "Hallo World";

	public void MyMethod()
	{
	
	}
}
```

change it too : 

```csharp
public class MyClass
{
	public string MyString;

	public void MyMethod()
	{
		MyString =  = "Hallo World";
	}
}
```

so **Obfuscar** can protect your string at methopd level.

As stated by @ZimM-LostPolygon a solution would be to make **Obfuscar** replacing class-level string by method-level string, initialization can be set in **.ctor()** method of the Class.

@lextm can be closed ?

**Comment by lextm** [comment]
@XenocodeRCE Thanks for the explanation. The details look cool, as I did not know them either.

**Comment by geroz9** [comment]
Moves strings from consts to the method. And this is whole protection? What is a user's profit?

**Comment by ZimM-LostPolygon** [comment]
@geroz9 The profit is that strings are not readable as plain text anymore.

**Comment by geroz9** [comment]
IlSpy (2.3.1) displays these strings in method's body and it is still readable.

**Comment by ZimM-LostPolygon** [comment]
Can you please post a screenshot? If that's the case, that might be a bug.

**Comment by geroz9** [comment]
public class AClass {
	public string aString;
	public void AMethod() {
		this.aString = "This is the test string";
		Console.WriteLine(this.aString);
	}
}

Obfuscar output

Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
Loading project V:\[Temp3]\ConsoleApp3\ConsoleApp3\bin\Debug\netcoreapp2.0\out\ocar.xml...Processing assembl
: ConsoleApp3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Loading assemblies...Extra framework folders: Done.
hiding strings...
Renaming:  fields...parameters...properties...events...methods...types...Done.
Saving assemblies...Done.
Writing log file...Done.
Completed, 0,59 secs.

IlSpy 

using System;
namespace A
{
	public class a
	{
		public string A;
		public void A()
		{
			this.A = "This is the test string";
			Console.WriteLine(this.A);
		}
	}
}

Sorry for formatting but editor seems to be uncontrollable for me now.

**Comment by ZimM-LostPolygon** [comment]
I'll check. But... Are Issues gone from this repo? I can't seem to open 
this issue in the browser, are you seeing the same thing?

03.06.2018 20:12, geroz9 пишет:

**Comment by ZimM-LostPolygon** [comment]
@geroz9 
Can't reproduce. This is what I get:
```
	public class AClass
	{
		public string aString;

		public void AMethod()
		{
			this.aString = D3D7049F-97A1-4235-9553-B26FF04F91C5.A();
			Console.WriteLine(this.aString);
		}
	}
```
Can you show the XML configuration file? What Obfuscar version do you use?
