### ISSUE TITLE
Only Obfuscate Certain Types

### ISSUE THREAD

**Issue by TonyValenti** [lextm/obfuscar#125]
Hi All,
I have a library that I'm working on and I'd like to keep most of it public except for the licensing code.
How do I tell Obfuscar to only obfuscate certain types?

Also, the documentation has a few places that say "Obfuscar 2.2.9 is now available on NuGet! Please read the Getting Started instructions for installing the latest version from NuGet." however the instructions don't seem to have anything related to nuget in them.

**Comment by TonyValenti** [comment]
Here's my XML that I'm using.  This seems to still obfuscate everything:
````
<Obfuscator>

    <Var name="InPath"  value="..\__BUILD\" />
    <Var name="OutPath" value="..\__BUILD_OBFUSCATED\" />

    <Module file="$(InPath)\AlphaDrive.Windows.exe" />

    <SkipNamespace name="AlphaDrive*" />
    <SkipType rx=".*" />
  
    <ForceType name="AlphaDrive.Windows.Authentication.AlphaDriveForWindowsApplicationInfo" />
    <ForceType name="AlphaDrive.Windows.Authentication.AlphaDriveEnterpriseMigratorApplicationInfo" />
</Obfuscator>

````

**Comment by lextm** [comment]
Your XML file is invalid. Any tag like `<SkipNamespace>` should be children of `<Module>` node. Please read again our documentation,

http://docs.obfuscar.com/en/latest/getting-started/configuration.html#keeppublicapi-and-hideprivateapi
