### ISSUE TITLE
When use Vitevic.VitevicAssemblyEmbedder merge all the dependencies , Obfuscar  : Unable to resolve dependency:  MetroSet UI

### ISSUE THREAD

**Issue by maikebing** [lextm/obfuscar#126]
当我使用 Vitevic.VitevicAssemblyEmbedder 合并所有依赖项后一部分nuget引用的内容就会无法找到， 添加 nuget 包的路径虽然可以解决， 但似乎不够灵活，因为dll 升级后路径有变化

When I use Vitevic.VitevicAssemblyEmbedder merge all the dependencies part of the contents of the reference to nuget will not find the path to add nuget package although it can be solved but it seems not flexible enough because the dll path changes after the upgrade

https://marketplace.visualstudio.com/items?itemName=Vitevic.VitevicAssemblyEmbedder

1>  TCS.LaneFix -> D:\Works\TCSOA\TCS.LaneFix\bin\Debug\TCS.LaneFix.exe
1>  Note that Rollbar API is enabled by default to collect crashes. If you want to opt out, please run with -s switch
1>  Loading project D:\Works\TCSOA\TCS.LaneFix\Obfuscar.Settings.xml...Processing assembly: TCS.LaneFix, Version=5.16.0.111, Culture=neutral, PublicKeyToken=null
1>  Loading assemblies...Extra framework folders: 
1>  An error occurred during processing:
1>  Unable to resolve dependency:  MetroSet UI

**Comment by maikebing** [comment]
<AssemblySearchPath path="$(InPath)\..\..\..\packages\MetroSet_UI.1.0.2\lib\net40\" />

**Comment by maikebing** [comment]
`  <AssemblySearchPath path="$(InPath)\..\..\..\packages\MetroSet_UI.1.0.2\lib\net40\" />`

**Comment by lextm** [comment]
There is no way for Obfuscar (Mono Cecil) to scan NuGet package cache, and no need. Anyway you should have the necessary assemblies in the output folder before obfuscation.
