### ISSUE TITLE
[Question] There is a setting to obfuscate also private variables in a method?

### ISSUE THREAD

**Issue by gigios** [lextm/obfuscar#127]
I'm checking the different possibilities of the configuration file to obfuscate only a part of my library.
My question is related the variables defined inside a method, is it possible to 'rename' also these variables?

For example:
```csharp
public AuthEncryption()
	{
		byte[] password = this.A;
		byte[] bytes = Encoding.UTF8.GetBytes(46E49612-49BB-4211-928B-B8311479329C.F());
		Rfc2898DeriveBytes rfc2898DeriveBytes = new Rfc2898DeriveBytes(password, bytes, 1000);
		this.a = Encoding.UTF8.GetBytes(46E49612-49BB-4211-928B-B8311479329C.f());
		this.B = rfc2898DeriveBytes.GetBytes(32);
	}
```
In this example only the private fields in the class are 'renamed', the local variables are visible (in this example the array 'password').
Exists a way to rename also the local variables?

**Comment by gigios** [comment]
I'm sorry! I have seen now that the original name of the variable password was not '*password*'.
In this case the question is: how works the '**rename**' algorithm?
It's not clear how the obfuscar use 'password' as variable name in a method that manage the 'password' of my software :) where the variable name was NOT 'password' but 'chiave' (italian translation).

**Comment by lextm** [comment]
The decompilers are strong enough to make their guess on what the variable names should be, so Obfuscar won't be able to stop them.

Keep in mind that obfuscation only increases the difficulty to crack your applications, but not prevents it from happening.

**Comment by noctis0430** [comment]
> The decompilers are strong enough to make their guess on what the variable names should be

Do you mean the decompilers will be able to restore the name of the local variable even though Obfuscar has renamed them?

Sorry for waking up this old issue.
