### ISSUE TITLE
Skip anonymous types

### ISSUE THREAD

**Issue by virzak** [lextm/obfuscar#131]
Is there a way to skip obfuscation on anonymous types?

If I have the following code in assembly that gets obfuscated:
```csharp
c => new {c.Name, c.Description}
```
I will always get these properties obfuscated whether I skip obfuscation on the method, class or assembly.

the particular problem is that I can't use this library:
http://entityframework-extensions.net/column-input-expression

**Comment by lextm** [comment]
Please refer to #130
