### ISSUE TITLE
reverse engineering

### ISSUE THREAD

**Issue by umudduman** [lextm/obfuscar#138]
hi, im starting to using obfuscar for my app to obfuscate. by the time I have one question on my mind that after I obfusceted my app can other software engineers reverse my programme?
if someone could reply I'll be appriciate..

**Comment by lextm** [comment]
It is said loud and clear http://docs.obfuscar.com/en/latest/getting-started/basics.html#caveat

**Comment by umudduman** [comment]
hi lex

We want to use it as an application that will give you the best
performance. Is Obfuscar paid? Is there a paid version?

2018-04-28 15:19 GMT+03:00 umut duman <umudduman@gmail.com>:
