### ISSUE TITLE
hi lex

### ISSUE THREAD

**Issue by umudduman** [lextm/obfuscar#140]
We want to use it as an application that will give you the best performance. Is Obfuscar paid? Is there a paid version?

**Comment by lextm** [comment]
As you should see at GitHub, this project is free and open source. There is no paid version.

**Comment by umudduman** [comment]
hi lex

how are you?

I have obfuscar json deserialization problem. how can i solve it. can you
help me, please.


2018-05-04 4:53 GMT+03:00 Lex Li <notifications@github.com>:
