### ISSUE TITLE
JToken deserialization not working if DTO namespace is obfuscated

### ISSUE THREAD

**Issue by iniherna** [lextm/obfuscar#142]
We are using [JToken deserialization](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_ToObject__1.htm) from JSON to object in our project:

```
string jsonFile = File.ReadAllText("path/to/file.json");
JObject jObject = JObject.Parse(jsonFile);
JToken jToken = jObject.SelectToken("path.to.token");
CustomObject customObject = jToken.ToObject<CustomObject>();
```

Our custom DTO objects are defined in the DTO namespace,

With the default configuration in obfuscar.xml, the deserialized objects are empty:

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\in\path" />
  <Var name="OutPath" value=".\out\path" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Module file="$(InPath)\program.dll" />
</Obfuscator>
```

We are only able to make it work if we skip the DTO namespace where the object classes are defined:

```
<?xml version='1.0'?>
<Obfuscator>
  <Var name="InPath" value=".\in\path" />
  <Var name="OutPath" value=".\out\path" />
  <Var name="KeepPublicApi" value="false" />
  <Var name="HidePrivateApi" value="true" />
  <Module file="$(InPath)\program.dll">
    <SkipNamespace name="DTO" />
  </Module>
</Obfuscator>
```

Is there any way we can make the JToken serialization/deserialization work without excluding the DTO namespace?

**Comment by lextm** [comment]
Obfuscar itself won't be able to help. You might utilize serialization attributes to add more metadata for the runtime to know which properties to map a value to. Without such, by default the runtime uses name matching, which any obfuscation tool would break.

**Comment by iniherna** [comment]
Yes, finally we managed to make it work by adding the [JsonProperty](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonPropertyAttribute.htm) attribute and specifying each **PropertyName** the following way:

```
public class CustomObject
{
    [JsonProperty(PropertyName = "Property01")]
    public CustomProperty01 Property01 { get; set; }

    [JsonProperty(PropertyName = "Property02")]
    public CustomProperty02 Property02 { get; set; }
}
```

Thanks a lot for your help Lex! The issue can be closed.
