### ISSUE TITLE
SuppressIldasm setting has to be called SupressIldasm in config to work

### ISSUE THREAD

**Issue by stevenswallow** [lextm/obfuscar#56]
In Obfuscator.cs - Line 1493 - if (!Project.Settings.SupressIldasm) 

https://obfuscar.codeplex.com/wikipage?title=Configuration&referringTitle=Documentation says it should be "SuppressIldasm" so is missing getting set unless you change the setting to "SupressIdasm". 

Also wanted to say, thanks a lot for all your work on this library, has come in most handy.

**Comment by lextm** [comment]
Thanks. Fixed in 2.0.2 final release.
