### ISSUE TITLE
"protected internal" property/method is not skipped

### ISSUE THREAD

**Issue by mituha** [lextm/obfuscar#58]
Fixed at #26(?), but it does not work.

```
<Var name="KeepPublicApi" value="true" />
<Var name="HidePrivateApi" value="true" />
```

```
public class ScopeTest
{
	/// <summary>
	/// skipped
	/// </summary>
	public string PublicProperty
	{
		get { return "PublicProperty"; }
	}
	/// <summary>
	/// skipped
	/// </summary>
	/// <returns></returns>
	public string PublicMethod()
	{
		return "PublicMethod";
	}

	/// <summary>
	/// -> A
	/// </summary>
	internal protected string InternalProtectedProperty
	{
		get { return "InternalProtectedProperty"; }
	}
	/// <summary>
	/// -> a
	/// </summary>
	/// <returns></returns>
	internal protected string InternalProtectedMethod()
	{
		return "InternalProtectedMethod";
	}

	/// <summary>
	/// skipped
	/// </summary>
	protected string ProtectedProperty
	{
		get { return "ProtectedProperty"; }
	}

	/// <summary>
	/// skipped
	/// </summary>
	/// <returns></returns>
	protected string ProtectedMethod()
	{
		return "ProtectedProperty";
	}

	/// <summary>
	/// -> B
	/// </summary>
	private string PrivateProperty
	{
		get { return "PrivateProperty"; }
	}

	/// <summary>
	/// -> b
	/// </summary>
	/// <returns></returns>
	private string PrivateMethod()
	{
		return "PrivateMethod";
	}
}
```

**Comment by GF-Huang** [comment]
Issue still, obfuscar 2.2.30.

Code:

![image](https://user-images.githubusercontent.com/4510984/121934217-9c2f1400-cd79-11eb-9ac5-e9a20a0bc3f2.png)

Log:

![image](https://user-images.githubusercontent.com/4510984/121934354-cbde1c00-cd79-11eb-9ca1-6053e41368d7.png)

Exception:

![image](https://user-images.githubusercontent.com/4510984/121934497-f16b2580-cd79-11eb-9b96-3db1e53ce2ec.png)

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/121949581-33e92e00-cd8b-11eb-9759-9930e417d60f.png)

![image](https://user-images.githubusercontent.com/4510984/121949667-4f543900-cd8b-11eb-8c10-7f57034e3b53.png)

**Comment by GF-Huang** [comment]
It seems not skip the `internal` class override method which inherits from built-in .NET `class` or `interface`.

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/122033209-e7413980-ce02-11eb-9c15-984db9418aab.png)

![image](https://user-images.githubusercontent.com/4510984/122033308-fb853680-ce02-11eb-9dfc-d3d7a071ec4a.png)

![image](https://user-images.githubusercontent.com/4510984/122033385-0dff7000-ce03-11eb-9a0e-ed813ca738a0.png)
