### ISSUE TITLE
Specify that nuget package is a development dependency

### ISSUE THREAD

**Issue by michaelmelancon** [lextm/obfuscar#62]
Nuget tool packages should include the following within the metadata element in the nuspec:
`<developmentDependency>true</developmentDependency>`

This will mark obfuscar as a development dependency automatically in projects that use it. This will prevent it from being listed as a dependency of those projects. This allows authors of tools packages to chain development dependencies as well.

**Comment by lextm** [comment]
Thanks. Will update the package soon.
