### ISSUE TITLE
Support for delay signed assemblies

### ISSUE THREAD

**Issue by dzeitlin** [lextm/obfuscar#65]
Latest versions of Obfuscator not supporting delay signed assembly. This is the error:
```
Loading assemblies...Extra framework folders: Done.
hiding strings...
Renaming:  fields...parameters...properties...events...methods...types...Done.
Saving assemblies...
Unhandled Exception: System.ArgumentException: Unable to obtain public key for StrongNameKeyPair.
   at System.Reflection.StrongNameKeyPair.ComputePublicKey()
   at System.Reflection.StrongNameKeyPair.get_PublicKey()
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Obfuscar.Obfuscator.SaveAssemblies()
   at Obfuscar.Obfuscator.RunRules()
   at Obfuscar.Program.Main(String[] args)
```
If you need an actual snk key I can create one and attach it.
Obfuscator `2.0.10205.0` did worked and we are using it and can't upgrade.
Thanks

**Comment by lextm** [comment]
I could not reproduce this exact exception.

Can you share your xml configuration for Obfuscar, as well as some information about the delay signed assembly (which C# compiler is used to generate it, .NET Framework version and so on)? That might give me more insights. The snk key file is irrelevant here.

Also it would be helpful if you share some information on what you exactly need. It is very rare to obfuscate delay signed assemblies. Why do you need that? Meanwhile, do you want the obfuscated assemblies to be delayed signed or fully signed?

My testing uses a Roslyn generated delayed signed assembly (.NET 4.6.1), and Obfuscar latest build can obfuscate it with the following configuration and the obfuscated result is signed,
```
			string xml = String.Format(
							 @"<?xml version='1.0'?>" +
							 @"<Obfuscator>" +
							 @"<Var name='InPath' value='{0}' />" +
							 @"<Var name='OutPath' value='{1}' />" +
							 @"<Var name='KeyFile' value='$(InPath)\..\dockpanelsuite.snk' />" +
							 @"<Var name='HidePrivateApi' value='true' />" +
							 @"<Var name='KeepPublicApi' value='false' />" +
							 @"<Module file='$(InPath)\DelaySigned.dll' />" +
							 @"</Obfuscator>", TestHelper.InputPath, TestHelper.OutputPath);
```
`KeyFile` is required here, as Obfuscar will report another error message if it is missing,

```
Obfuscating a signed assembly would result in an invalid assembly:  DelaySigned; use the KeyFile property to set a key to use
```

**Comment by dzeitlin** [comment]
Thanks for your replay, I am sending you the files to reproduce the problem.
Again in `Obfuscar 2.0.10205.0` it just works.
HelloWorld.exe is one line console app, delay signed using the attached **shared key**.
Running latest Obfuscar result in the error above.
`Obfuscar.Console.exe obfuscator.xml`

[hello world delay signed with shared key.zip](https://github.com/lextm/obfuscar/files/201185/hello.world.delay.signed.with.shared.key.zip)

Thanks.

**Comment by lextm** [comment]
I tested your assembly (original) but it is not even a valid assembly for sn.exe.
```
sn -v HelloWorld.original.exe

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```
Thus, I probably don't plan to support such assemblies.

A valid delay signed assembly should trigger,
```
sn -v DelaySigned.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

DelaySigned.dll is a delay-signed or test-signed assembly
```
I wonder from which compiler you got such an assembly.
