### ISSUE TITLE
How to exclude all subclasses of the special class

### ISSUE THREAD

**Issue by cqgreen** [lextm/obfuscar#66]
I use obfuscar in Unity3d. For some reason, I have to exclude all subclasses of MonoBehaviour. Now I add ObfuscationAttribute(Exclude=true) at every MonoBehaviour class. 

Is there better way to exclude all subclasses of the special class? 
thanks

**Comment by lextm** [comment]
You can use exclusion rules in configuration,

http://obfuscar.codeplex.com/wikipage?title=Configuration

**Comment by cqgreen** [comment]
Sorry. I tryed all skipXXX elmemnts. No one can exclude subclasses of the special class.

**Comment by lextm** [comment]
Skip rule supports regular expressions so Yu can skip such classes by using a regular expression that matches all of their names. Of course wildcard can also be used as an alternative way.
