### ISSUE TITLE
cannot obfuscate forms

### ISSUE THREAD

**Issue by patrickst81** [lextm/obfuscar#67]
I have successfully obfuscated parts of my GUI application and it's just working fine. However, if I also want to obfuscate forms that are opened with ShowDialog() then there will be thrown an unhandled exception like "could not find A.o.resources". In my Mapping.txt I can see that the resource is skipped with "no clear new name". The type is renamed, but not the resource which I think causes the trouble.

**Comment by lextm** [comment]
I used this obfuscator a lot in my projects, which do not lead to such exceptions. Can you provide a small sample which can reproduce the issue?

**Comment by patrickst81** [comment]
Of course, you'll find a demonstration app in the attachment. You should get an exception by clicking on "Open Dialog" using the obfuscated exe.
[WindowsApplication.zip](https://github.com/lextm/obfuscar/files/203097/WindowsApplication.zip)

**Comment by patrickst81** [comment]
Found a workaround to my problem by replacing the following line 
`Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)` with
`Me.Icon = Global.WindowsApplication.My.Resources.Options`
in `MyDialog.Designer.vb`
