### ISSUE TITLE
Skipping a single function in a namespace\class

### ISSUE THREAD

**Issue by themike10452** [lextm/obfuscar#75]
**Help Needed**

I am trying to obfuscate a c# Web Project. Each page has an entry point with following signature:
protected void Page_Load(object sender, EventArgs e)

This function should not be renamed, because the page will no longer work and it will throw an exception. How is it possible to exclude this function without using KeepPublicApi=true because I need other public function names to be obfuscated in that same class.
I tried <SkipType name="namespace\class\Page_Load" /> but that doesn't seem to affect functions and methods. So is it even possible?

Any help would be appreciated.

**Comment by lextm** [comment]
Exclusion rules can help, http://obfuscar.codeplex.com/wikipage?title=Configuration

**Comment by themike10452** [comment]
@lextm How to make it work on functions? Not an entire namespace or class ...

**Comment by lextm** [comment]
`SkipMethod`.
