### ISSUE TITLE
Failed to resolve assembly: 'EntityFramework, Version=6.0.0.0, Culture=neutral

### ISSUE THREAD

**Issue by oSilas** [lextm/obfuscar#77]
1>  TBQQ.Robot -> D:\Works\TBKQQRobot\TBQQ\TBQQ.Robot\bin\Debug\TBQQ.Robot.exe
1>  Loading project D:\Works\TBKQQRobot\TBQQ\TBQQ.Robot\Obfuscar.Settings.xml...
1>  An error occurred during processing:
1>  Unable to find assembly:  .\TBQQ.Robot.exe
1>  Failed to resolve assembly: 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: 命令“D:\Works\TBKQQRobot\TBQQ\packages\Obfuscar.2.2.0\tools\Obfuscar.Console.exe D:\Works\TBKQQRobot\TBQQ\TBQQ.Robot\Obfuscar.Settings.xml”已退出，代码为 1。

**Comment by oSilas** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<Obfuscator>
  <Var name="InPath" value="." />
  <Var name="OutPath" value=".\Obfuscated" />
  <Var name="LogFile" value="$(OutPath)\Mappings.xml" />

  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="ReuseNames" value="true" />
  <Var name="RegenerateDebugInfo" value="false" />
  <Var name="XmlMapping" value="true" />
  <Var name="HideStrings" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="UseUnicodeNames" value="true" />
  <Var name="UseKoreanNames" value="false" />
  <Var name="RenameProperties " value="true" />
  <Var name="OptimizedMethods " value="true" />
  
  <Module file="$(InPath)\TBQQ.Robot.exe" />
</Obfuscator>

**Comment by oSilas** [comment]
必须要将 'EntityFramework, 设置为本地才可以 混淆成功。

**Comment by lextm** [comment]
As you found out, Obfuscar only attempts to resolve local dependencies and will not check GAC. So assemblies must be present in local folders and set  Copy Local to true in your project files.
