### ISSUE TITLE
Incorrect result for MethodKey.MethodMatch()

### ISSUE THREAD

**Issue by Yves57** [lextm/obfuscar#78]
I have the following case:
```
public IInterface1 { void M(int i); }
internal class MyImpl1 : IInterface1 { void M(int i) { } }
internal class OtherClass { void M(int i) { } }
```
All these methods are grouped in only one `MethodGroup`, and it fails in `RenameVirtualMethod` (Inconsistent virtual method obfuscation state detected).

**Comment by lextm** [comment]
https://blog.lextudio.com/2014/09/obfuscar-the-story-behind-inconsistent-virtual-method-obfuscation-state-detected/

The technical details are in the post.
