### ISSUE TITLE
mysetting.xxxConnectionString is not accessible

### ISSUE THREAD

**Issue by Mastericarus333** [lextm/obfuscar#81]
If i add in my project a data source by data sources Windows (automatically Visual Studio make PersonalConnectionString in mysetting)
When i use obfuscar with RenameProperties option to true, when i lauch my aplication "PersonalConnectionString proprierties is missing" and application fail to start

System.Configuration.SettingsPropertyNotFoundException: Impossibile trovare la proprietà di impostazione 'MarketingConnectionString'.
   in System.Configuration.SettingsBase.SetPropertyValueByName(String propertyName, Object propertyValue)
   in System.Configuration.SettingsBase.set_Item(String propertyName, Object value)
   in System.Configuration.ApplicationSettingsBase.set_Item(String propertyName, Object value)
   in 픻.픵.핵(Object , EventArgs )
   in System.EventHandler.Invoke(Object sender, EventArgs e)
   in System.Windows.Forms.Form.OnLoad(EventArgs e)
   in System.Windows.Forms.Form.OnCreateControl()
   in System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   in System.Windows.Forms.Control.CreateControl()
   in System.Windows.Forms.Control.WmShowWindow(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.Form.WmShowWindow(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1080.0 built by: NETFXREL3STAGE
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Axel
    Versione assembly: 1.0.0.6
    Versione Win32: 1.0.0.6
    Base di codice: file:///C:/Users/dimec/Desktop/Debug/Obfuscated/Axel.exe
----------------------------------------
Microsoft.VisualBasic
    Versione assembly: 10.0.0.0
    Versione Win32: 14.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1081.0 built by: NETFXREL3STAGE
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1078.0 built by: NETFXREL3STAGE
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1064.2 built by: NETFXREL3STAGE
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Axel_DLL
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
    Base di codice: file:///C:/Users/dimec/Desktop/Debug/Obfuscated/Axel_DLL.DLL
----------------------------------------
System.Data
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.DataSetExtensions
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
System.Numerics
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1038.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

Please verify this issue

**Comment by lextm** [comment]
Since it is something caused by .NET Framework itself, you have to exclude the certain property or properties from being renamed.

Multiple ways to do so, such as using exclusion rules,

https://obfuscar.codeplex.com/wikipage?title=Configuration
