### ISSUE TITLE
'private' is not valid for the 'attrib' value of skip elements.

### ISSUE THREAD

**Issue by tom-seddon** [lextm/obfuscar#84]
You can exclude such elements using `ObfuscationAttribute` - why not from inside the config file?

If you're working with 3rd party non-open code, you might want to keep the source code unmodified so that you don't need to keep reapplying the same changes in future.

Thanks,

--Tom

**Comment by lextm** [comment]
Thanks for the report. Can you briefly describe what exactly you were doing so that I can create a suitable unit test case to reproduce it?

**Comment by lextm** [comment]
Temp close unless more info is provided.
