### ISSUE TITLE
How to obfuscate a series of dependent dlls

### ISSUE THREAD

**Issue by scpc0609** [lextm/obfuscar#89]
Thanks for the great project. I wanted to know how can I obfuscate between a series of dependent dlls.

eg.
Dll-1: public class SomeClass got renamed to class A
Dll-2: dependent on Dll-1.SomeClass. So, change all references of SomeClass to class A.

and so on...

**Comment by cail** [comment]
The project is really great, agree!

From my experience as soon as you obfuscate these DLLs all in the same run, obfuscar takes care of fixing the linkage.

The only exception is of course reflection usage of types.
