### ISSUE TITLE
When ForceNamespace is used, HideStrings setting is ignored.

### ISSUE THREAD

**Issue by cruxic** [lextm/obfuscar#90]
Strings are still hidden despite HideStrings being set to false when ForceNamespace is used (and probably other ForceX directives).  This is counter to the documentation which says

> By default Obfuscar hides all string constants by ... You can **disable this feature completely** by adding the following line to the configuration file:  `<Var name="HideStrings" value="false" />`

For example:
`
<?xml version='1.0'?>
<Obfuscator>
    <Var name="InPath" value=".\bin\Release" />
    <Var name="OutPath" value=".\bin\Obfuscated" />

    <Var name="KeepPublicApi" value="false" />
    <Var name="HidePrivateApi" value="true" />  
        
    <Var name="HideStrings" value="false" />

    <Module file="$(InPath)\foobar.exe">
        <SkipNamespace name="*"/>       
        <ForceNamespace name="my_secret_namespace*"/>
    </Module>
</Obfuscator>
`

**Comment by lextm** [comment]
Force namespace rules take highest priority, so this behavior is by design.

If you do want to fine tune the obfuscation result, you have to give up "ForceNamespace" and use a set of smaller force rules (which properly sets hide string flag).
