### ISSUE TITLE
Program gets InvalidProgramException after obfuscation

### ISSUE THREAD

**Issue by cruxic** [lextm/obfuscar#92]
After obfuscation with Obfuscar 2.2.2, [this program](https://github.com/lextm/obfuscar/files/640383/Crash-bug.zip) crashes with the exception:

`System.InvalidProgramException: Common Language Runtime detected an invalid program.`

Target Framework: 4.0 or 4.5 or 4.6  (it doesn't seem to matter)
OS: Windows 10 with all updates
Runtime Framework: 4.6.1
Visual Studio Pro 2015

I have made the program as simple as possible.  Perhaps one clue is that, renaming the "videx_obfuscated" namespace avoids the crash.

To reproduce:
1. Extract the zip
2. Copy Obfuscar.Console.exe into the folder
3. Open the solution and compile it in Release mode
4. Open a command window
5. Execute run.bat  (which will obfuscate and then execute it)

**Comment by cruxic** [comment]
By the way, thank you so much for providing the community with this high quality tool!

**Comment by lextm** [comment]
Thanks. It is related to string hiding, which I have to temporarily disable in 2.2.3. You can update your Obfuscar to that version. Since string hiding can be easily reversed, enabling/disabling it does not bring much differences.

**Comment by ZimM-LostPolygon** [comment]
https://github.com/lextm/obfuscar/pull/101 should have fixed this.
