### ISSUE TITLE
Obfuscating dll of an asp.net mvc web application is not working.

### ISSUE THREAD

**Issue by amjadhussen** [lextm/obfuscar#93]
When I obfuscate the dll of a asp.net mvc web application. It obfuscates successfully. however after obfuscating if I run the application it gives 403.14 forbidden error.

**Comment by lextm** [comment]
Framework like ASP.NET MVC rely on naming conventions to locate controllers and views. You have to exclude such classes and properties out of obfuscation manually.

**Comment by amjadhussen** [comment]
If I obfuscate only one class and the object of this class is created in controller. Will that break the flow.

**Comment by lextm** [comment]
It is quite common to exclude some classes or class members, so usually there should be no issue. Besides, why do you have to obfuscate an ASP.NET MVC app? Such server side applications usually do not expose assemblies to end users and obfuscation is usually unnecessary.

**Comment by amjadhussen** [comment]
The server on which the code will be is on client side.
