### ISSUE TITLE
Missing Baml.csproj file

### ISSUE THREAD

**Issue by TBomberman** [lextm/obfuscar#96]
There's a whole bunch of missing cs files in Baml.csproj. https://github.com/lextm/obfuscar/blob/master/Baml/Baml.csproj#L61-L131

As a result, I can't even try the included example.

**Comment by licinioamendes** [comment]
It's needed to execute the following commands on repository root:
`git submodule update --init --recursive`
`.\.nuget\nuget.exe restore Obfuscar.sln`

then open the solution and build it. After that it is possible to run the test.bat file from examples.

**Comment by yakkobr** [comment]
Not working.

PS C:\Users\user\Desktop\projects\obfuscators\obfuscar> git submodule update --init --recursive
fatal: Needed a single revision
Unable to find current revision in submodule path 'ThirdParty/ILSpy'
